-- 0027_seed_iso4217_currencies.sql
-- Seed all major ISO 4217 currencies into the currencies table.
-- Uses INSERT IGNORE to be idempotent — existing currencies are preserved.

INSERT IGNORE INTO `currencies` (`currencyName`, `currencyCode`, `currencySymbol`, `status`, `createdAt`, `updatedAt`) VALUES
('Afghan Afghani', 'AFN', '؋', 'true', NOW(), NOW()),
('Albanian Lek', 'ALL', 'L', 'true', NOW(), NOW()),
('Algerian Dinar', 'DZD', 'د.ج', 'true', NOW(), NOW()),
('Angolan Kwanza', 'AOA', 'Kz', 'true', NOW(), NOW()),
('Argentine Peso', 'ARS', '$', 'true', NOW(), NOW()),
('Armenian Dram', 'AMD', '֏', 'true', NOW(), NOW()),
('Australian Dollar', 'AUD', 'A$', 'true', NOW(), NOW()),
('Azerbaijani Manat', 'AZN', '₼', 'true', NOW(), NOW()),
('Bahamian Dollar', 'BSD', 'B$', 'true', NOW(), NOW()),
('Bahraini Dinar', 'BHD', 'BD', 'true', NOW(), NOW()),
('Bangladeshi Taka', 'BDT', '৳', 'true', NOW(), NOW()),
('Barbadian Dollar', 'BBD', 'Bds$', 'true', NOW(), NOW()),
('Belarusian Ruble', 'BYN', 'Br', 'true', NOW(), NOW()),
('Belize Dollar', 'BZD', 'BZ$', 'true', NOW(), NOW()),
('Bhutanese Ngultrum', 'BTN', 'Nu', 'true', NOW(), NOW()),
('Bolivian Boliviano', 'BOB', 'Bs.', 'true', NOW(), NOW()),
('Bosnia-Herzegovina Mark', 'BAM', 'KM', 'true', NOW(), NOW()),
('Botswana Pula', 'BWP', 'P', 'true', NOW(), NOW()),
('Brazilian Real', 'BRL', 'R$', 'true', NOW(), NOW()),
('British Pound', 'GBP', '£', 'true', NOW(), NOW()),
('Brunei Dollar', 'BND', 'B$', 'true', NOW(), NOW()),
('Bulgarian Lev', 'BGN', 'лв', 'true', NOW(), NOW()),
('Burundian Franc', 'BIF', 'Fr', 'true', NOW(), NOW()),
('Cambodian Riel', 'KHR', '៛', 'true', NOW(), NOW()),
('Canadian Dollar', 'CAD', 'CA$', 'true', NOW(), NOW()),
('Cape Verdean Escudo', 'CVE', '$', 'true', NOW(), NOW()),
('Cayman Islands Dollar', 'KYD', '$', 'true', NOW(), NOW()),
('Central African CFA Franc', 'XAF', 'Fr', 'true', NOW(), NOW()),
('Chilean Peso', 'CLP', '$', 'true', NOW(), NOW()),
('Chinese Yuan', 'CNY', '¥', 'true', NOW(), NOW()),
('Colombian Peso', 'COP', '$', 'true', NOW(), NOW()),
('Comorian Franc', 'KMF', 'Fr', 'true', NOW(), NOW()),
('Congolese Franc', 'CDF', 'Fr', 'true', NOW(), NOW()),
('Costa Rican Colón', 'CRC', '₡', 'true', NOW(), NOW()),
('Croatian Kuna', 'HRK', 'kn', 'true', NOW(), NOW()),
('Cuban Peso', 'CUP', '$', 'true', NOW(), NOW()),
('Czech Koruna', 'CZK', 'Kč', 'true', NOW(), NOW()),
('Danish Krone', 'DKK', 'kr', 'true', NOW(), NOW()),
('Djiboutian Franc', 'DJF', 'Fr', 'true', NOW(), NOW()),
('Dominican Peso', 'DOP', 'RD$', 'true', NOW(), NOW()),
('Egyptian Pound', 'EGP', '£', 'true', NOW(), NOW()),
('Eritrean Nakfa', 'ERN', 'Nfk', 'true', NOW(), NOW()),
('Ethiopian Birr', 'ETB', 'Br', 'true', NOW(), NOW()),
('Euro', 'EUR', '€', 'true', NOW(), NOW()),
('Falkland Islands Pound', 'FKP', '£', 'true', NOW(), NOW()),
('Fijian Dollar', 'FJD', 'FJ$', 'true', NOW(), NOW()),
('Gambian Dalasi', 'GMD', 'D', 'true', NOW(), NOW()),
('Georgian Lari', 'GEL', '₾', 'true', NOW(), NOW()),
('Ghanaian Cedi', 'GHS', '₵', 'true', NOW(), NOW()),
('Guatemalan Quetzal', 'GTQ', 'Q', 'true', NOW(), NOW()),
('Guinean Franc', 'GNF', 'Fr', 'true', NOW(), NOW()),
('Guyanese Dollar', 'GYD', '$', 'true', NOW(), NOW()),
('Haitian Gourde', 'HTG', 'G', 'true', NOW(), NOW()),
('Honduran Lempira', 'HNL', 'L', 'true', NOW(), NOW()),
('Hong Kong Dollar', 'HKD', 'HK$', 'true', NOW(), NOW()),
('Hungarian Forint', 'HUF', 'Ft', 'true', NOW(), NOW()),
('Icelandic Króna', 'ISK', 'kr', 'true', NOW(), NOW()),
('Indian Rupee', 'INR', '₹', 'true', NOW(), NOW()),
('Indonesian Rupiah', 'IDR', 'Rp', 'true', NOW(), NOW()),
('Iranian Rial', 'IRR', '﷼', 'true', NOW(), NOW()),
('Iraqi Dinar', 'IQD', 'ع.د', 'true', NOW(), NOW()),
('Israeli New Shekel', 'ILS', '₪', 'true', NOW(), NOW()),
('Jamaican Dollar', 'JMD', 'J$', 'true', NOW(), NOW()),
('Japanese Yen', 'JPY', '¥', 'true', NOW(), NOW()),
('Jordanian Dinar', 'JOD', 'JD', 'true', NOW(), NOW()),
('Kazakhstani Tenge', 'KZT', '₸', 'true', NOW(), NOW()),
('Kenyan Shilling', 'KES', 'KSh', 'true', NOW(), NOW()),
('Kuwaiti Dinar', 'KWD', 'KD', 'true', NOW(), NOW()),
('Kyrgyzstani Som', 'KGS', 'с', 'true', NOW(), NOW()),
('Laotian Kip', 'LAK', '₭', 'true', NOW(), NOW()),
('Lebanese Pound', 'LBP', 'ل.ل', 'true', NOW(), NOW()),
('Lesotho Loti', 'LSL', 'L', 'true', NOW(), NOW()),
('Liberian Dollar', 'LRD', '$', 'true', NOW(), NOW()),
('Libyan Dinar', 'LYD', 'LD', 'true', NOW(), NOW()),
('Macanese Pataca', 'MOP', 'P', 'true', NOW(), NOW()),
('Malagasy Ariary', 'MGA', 'Ar', 'true', NOW(), NOW()),
('Malawian Kwacha', 'MWK', 'MK', 'true', NOW(), NOW()),
('Malaysian Ringgit', 'MYR', 'RM', 'true', NOW(), NOW()),
('Maldivian Rufiyaa', 'MVR', 'Rf', 'true', NOW(), NOW()),
('Mauritanian Ouguiya', 'MRU', 'UM', 'true', NOW(), NOW()),
('Mauritian Rupee', 'MUR', 'Rs', 'true', NOW(), NOW()),
('Mexican Peso', 'MXN', '$', 'true', NOW(), NOW()),
('Moldovan Leu', 'MDL', 'L', 'true', NOW(), NOW()),
('Mongolian Tögrög', 'MNT', '₮', 'true', NOW(), NOW()),
('Moroccan Dirham', 'MAD', 'MAD', 'true', NOW(), NOW()),
('Mozambican Metical', 'MZN', 'MT', 'true', NOW(), NOW()),
('Myanmar Kyat', 'MMK', 'K', 'true', NOW(), NOW()),
('Namibian Dollar', 'NAD', '$', 'true', NOW(), NOW()),
('Nepalese Rupee', 'NPR', 'Rs', 'true', NOW(), NOW()),
('New Taiwan Dollar', 'TWD', 'NT$', 'true', NOW(), NOW()),
('New Zealand Dollar', 'NZD', 'NZ$', 'true', NOW(), NOW()),
('Nicaraguan Córdoba', 'NIO', 'C$', 'true', NOW(), NOW()),
('Nigerian Naira', 'NGN', '₦', 'true', NOW(), NOW()),
('Norwegian Krone', 'NOK', 'kr', 'true', NOW(), NOW()),
('Omani Rial', 'OMR', 'ر.ع.', 'true', NOW(), NOW()),
('Pakistani Rupee', 'PKR', 'Rs', 'true', NOW(), NOW()),
('Panamanian Balboa', 'PAB', 'B/.', 'true', NOW(), NOW()),
('Papua New Guinean Kina', 'PGK', 'K', 'true', NOW(), NOW()),
('Paraguayan Guaraní', 'PYG', '₲', 'true', NOW(), NOW()),
('Peruvian Sol', 'PEN', 'S/.', 'true', NOW(), NOW()),
('Philippine Peso', 'PHP', '₱', 'true', NOW(), NOW()),
('Polish Zloty', 'PLN', 'zł', 'true', NOW(), NOW()),
('Qatari Riyal', 'QAR', 'ر.ق', 'true', NOW(), NOW()),
('Romanian Leu', 'RON', 'lei', 'true', NOW(), NOW()),
('Russian Ruble', 'RUB', '₽', 'true', NOW(), NOW()),
('Rwandan Franc', 'RWF', 'Fr', 'true', NOW(), NOW()),
('São Tomé and Príncipe Dobra', 'STN', 'Db', 'true', NOW(), NOW()),
('Saudi Riyal', 'SAR', 'ر.س', 'true', NOW(), NOW()),
('Serbian Dinar', 'RSD', 'дин', 'true', NOW(), NOW()),
('Seychellois Rupee', 'SCR', 'Rs', 'true', NOW(), NOW()),
('Sierra Leonean Leone', 'SLL', 'Le', 'true', NOW(), NOW()),
('Singapore Dollar', 'SGD', 'S$', 'true', NOW(), NOW()),
('Solomon Islands Dollar', 'SBD', '$', 'true', NOW(), NOW()),
('Somali Shilling', 'SOS', 'Sh', 'true', NOW(), NOW()),
('South African Rand', 'ZAR', 'R', 'true', NOW(), NOW()),
('South Korean Won', 'KRW', '₩', 'true', NOW(), NOW()),
('South Sudanese Pound', 'SSP', '£', 'true', NOW(), NOW()),
('Sri Lankan Rupee', 'LKR', 'Rs', 'true', NOW(), NOW()),
('Sudanese Pound', 'SDG', 'ج.س.', 'true', NOW(), NOW()),
('Swazi Lilangeni', 'SZL', 'L', 'true', NOW(), NOW()),
('Swedish Krona', 'SEK', 'kr', 'true', NOW(), NOW()),
('Swiss Franc', 'CHF', 'Fr', 'true', NOW(), NOW()),
('Syrian Pound', 'SYP', 'ل.س', 'true', NOW(), NOW()),
('Tajikistani Somoni', 'TJS', 'SM', 'true', NOW(), NOW()),
('Tanzanian Shilling', 'TZS', 'TSh', 'true', NOW(), NOW()),
('Thai Baht', 'THB', '฿', 'true', NOW(), NOW()),
('Tongan Paʻanga', 'TOP', 'T$', 'true', NOW(), NOW()),
('Trinidad and Tobago Dollar', 'TTD', 'TT$', 'true', NOW(), NOW()),
('Tunisian Dinar', 'TND', 'DT', 'true', NOW(), NOW()),
('Turkish Lira', 'TRY', '₺', 'true', NOW(), NOW()),
('Turkmenistani Manat', 'TMT', 'T', 'true', NOW(), NOW()),
('Ugandan Shilling', 'UGX', 'USh', 'true', NOW(), NOW()),
('Ukrainian Hryvnia', 'UAH', '₴', 'true', NOW(), NOW()),
('United Arab Emirates Dirham', 'AED', 'د.إ', 'true', NOW(), NOW()),
('United States Dollar', 'USD', '$', 'true', NOW(), NOW()),
('Uruguayan Peso', 'UYU', '$U', 'true', NOW(), NOW()),
('Uzbekistani Som', 'UZS', 'сум', 'true', NOW(), NOW()),
('Vanuatu Vatu', 'VUV', 'Vt', 'true', NOW(), NOW()),
('Venezuelan Bolívar', 'VES', 'Bs.S', 'true', NOW(), NOW()),
('Vietnamese Dong', 'VND', '₫', 'true', NOW(), NOW()),
('West African CFA Franc', 'XOF', 'Fr', 'true', NOW(), NOW()),
('Yemeni Rial', 'YER', '﷼', 'true', NOW(), NOW()),
('Zambian Kwacha', 'ZMW', 'ZK', 'true', NOW(), NOW()),
('Zimbabwean Dollar', 'ZWL', '$', 'true', NOW(), NOW());
