CREATE TABLE IF NOT EXISTS `hr_payrolls` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` bigint NOT NULL DEFAULT 1,
  `userId` bigint NOT NULL,
  `contractId` bigint NULL,
  `period` varchar(20) NOT NULL,
  `currencyId` bigint NULL,
  `baseSalary` double NOT NULL DEFAULT 0,
  `transportAllowance` double NOT NULL DEFAULT 0,
  `housingAllowance` double NOT NULL DEFAULT 0,
  `riskAllowance` double NOT NULL DEFAULT 0,
  `otherAllowances` double NOT NULL DEFAULT 0,
  `overtimeHours` double NOT NULL DEFAULT 0,
  `overtimeAmount` double NOT NULL DEFAULT 0,
  `unpaidAbsenceDeduction` double NOT NULL DEFAULT 0,
  `advanceDeduction` double NOT NULL DEFAULT 0,
  `taxAmount` double NOT NULL DEFAULT 0,
  `cnssAmount` double NOT NULL DEFAULT 0,
  `otherDeductions` double NOT NULL DEFAULT 0,
  `grossSalary` double NOT NULL DEFAULT 0,
  `netSalary` double NOT NULL DEFAULT 0,
  `workedDays` double NOT NULL DEFAULT 0,
  `absenceDays` double NOT NULL DEFAULT 0,
  `paidLeaveDays` double NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'draft',
  `notes` text NULL,
  `created_at` timestamp NULL,
  `updated_at` timestamp NULL,
  CONSTRAINT `hr_payrolls_id` PRIMARY KEY(`id`),
  INDEX `idx_hr_payrolls_user` (`userId`),
  INDEX `idx_hr_payrolls_period` (`period`),
  INDEX `idx_hr_payrolls_status` (`status`)
);
