CREATE TABLE IF NOT EXISTS `hr_attendances` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` bigint NOT NULL DEFAULT 1,
  `userId` bigint NOT NULL,
  `workDate` date NOT NULL,
  `shiftId` bigint,
  `clockIn` varchar(20),
  `pauseOut` varchar(20),
  `pauseIn` varchar(20),
  `clockOut` varchar(20),
  `workedHours` double NOT NULL DEFAULT 0,
  `lateMinutes` int NOT NULL DEFAULT 0,
  `overtimeHours` double NOT NULL DEFAULT 0,
  `absenceHours` double NOT NULL DEFAULT 0,
  `source` varchar(30) NOT NULL DEFAULT 'manual',
  `status` varchar(30) NOT NULL DEFAULT 'present',
  `note` text,
  `created_at` timestamp,
  `updated_at` timestamp,
  CONSTRAINT `hr_attendances_id` PRIMARY KEY(`id`),
  INDEX `idx_hr_attendances_user_date` (`userId`, `workDate`),
  INDEX `idx_hr_attendances_shift` (`shiftId`),
  INDEX `idx_hr_attendances_status` (`status`)
);
