CREATE TABLE IF NOT EXISTS `hr_candidates` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` bigint NOT NULL DEFAULT 1,
  `offerId` bigint DEFAULT NULL,
  `firstName` varchar(180) NOT NULL,
  `lastName` varchar(180) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(80) DEFAULT NULL,
  `nationality` varchar(120) DEFAULT NULL,
  `gender` varchar(40) DEFAULT NULL,
  `birthDate` date DEFAULT NULL,
  `currentTitle` varchar(180) DEFAULT NULL,
  `currentEmployer` varchar(180) DEFAULT NULL,
  `yearsExperience` double DEFAULT NULL,
  `educationLevel` varchar(120) DEFAULT NULL,
  `skills` text,
  `languages` varchar(500) DEFAULT NULL,
  `source` varchar(120) DEFAULT NULL,
  `cvUrl` varchar(500) DEFAULT NULL,
  `portfolioUrl` varchar(500) DEFAULT NULL,
  `linkedinUrl` varchar(500) DEFAULT NULL,
  `coverLetterUrl` varchar(500) DEFAULT NULL,
  `stage` varchar(50) NOT NULL DEFAULT 'nouveau',
  `rating` double DEFAULT NULL,
  `interviewDate` date DEFAULT NULL,
  `testDate` date DEFAULT NULL,
  `offerDate` date DEFAULT NULL,
  `offerAmount` double DEFAULT NULL,
  `offerCurrencyId` bigint DEFAULT NULL,
  `convertedUserId` bigint DEFAULT NULL,
  `convertedAt` timestamp NULL DEFAULT NULL,
  `assignedTo` bigint DEFAULT NULL,
  `decisionComment` text,
  `status` varchar(30) NOT NULL DEFAULT 'active',
  `notes` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_hr_candidates_offer` (`offerId`),
  INDEX `idx_hr_candidates_stage` (`stage`)
);
