-- Idempotent (INSERT IGNORE + UNIQUE org+name). Seed de vaccins ANIMAUX courants (org 1).
-- Donnees indicatives d'apres notices veterinaires publiques (WOAH/OIE, FAO, fabricants, WSAVA).
-- A verifier/adapter par un veterinaire avant usage terrain (cf. avertissement UI). Pas d'apostrophe.
INSERT IGNORE INTO `farmos_vaccines`
  (`organization_id`,`name`,`commercial_names`,`manufacturer`,`species`,`target_diseases`,`vaccine_type`,`dose`,`route`,`primo_age`,`booster_schedule`,`protection_duration`,`treatment_duration`,`withdrawal_meat`,`withdrawal_milk`,`withdrawal_eggs`,`side_effects`,`contraindications`,`precautions`,`storage`,`packaging`,`source_url`,`is_seed`)
VALUES
  (1,'Newcastle (ND) - souche La Sota','Avinew, Nobilis ND','Ceva / MSD','poultry','Maladie de Newcastle','vivant attenue','1 dose/sujet','eau de boisson, nebulisation ou oculo-nasal','jour 1 a 7','rappel a 3-4 semaines puis toutes 8-12 semaines','6-12 semaines','programme repete selon elevage','0 jour',NULL,'0 jour','leger abattement transitoire, baisse de ponte passagere','sujets malades ou immunodeprimes','chaine du froid, eau sans chlore ni desinfectant pour voie orale','+2 a +8 C, a l abri de la lumiere','flacon lyophilise 1000-5000 doses','https://www.woah.org/fr/maladie/maladie-de-newcastle/',1),
  (1,'Gumboro (IBD)','Bursine, Nobilis Gumboro','Boehringer / MSD','poultry','Maladie de Gumboro (bursite infectieuse)','vivant attenue intermediaire','1 dose/sujet','eau de boisson','10 a 21 jours','rappel selon pression virale','plusieurs semaines','dose unique ou double selon protocole','0 jour',NULL,'0 jour','immunodepression transitoire de la bourse','poussins a anticorps maternels eleves (ajuster la date)','respecter la date optimale (courbe de Deventer)','+2 a +8 C','flacon 1000-2500 doses','https://www.woah.org/fr/maladie/bursite-infectieuse-aviaire/',1),
  (1,'Bronchite infectieuse (IB) - H120','Nobilis IB H120','MSD','poultry','Bronchite infectieuse aviaire','vivant attenue','1 dose/sujet','eau de boisson, spray ou oculo-nasal','jour 1','rappel 2-3 semaines puis selon programme','6-8 semaines','programme repete','0 jour',NULL,'0 jour','jetage leger, eternuements transitoires','sujets malades','associer aux souches variantes selon region','+2 a +8 C','flacon 1000-5000 doses','https://www.woah.org/fr/maladie/bronchite-infectieuse-aviaire/',1),
  (1,'Variole aviaire (Fowl pox)','Diftosec, Nobilis Pox','Ceva / MSD','poultry','Variole aviaire','vivant attenue','1 dose','transfixion alaire (wing-web)','6 a 10 semaines','rappel annuel','12 mois','dose unique','0 jour',NULL,'0 jour','reaction locale au point d inoculation (papule)','poussins trop jeunes','verifier la prise (papule a J7-10)','+2 a +8 C','flacon + diluant + applicateur','https://www.woah.org/fr/maladie/variole-aviaire/',1),
  (1,'Mycoplasmose aviaire (MG)','Nobilis MG 6/85','MSD','poultry','Mycoplasma gallisepticum','vivant attenue','1 dose','spray fin (aerosol)','plus de 6 semaines','selon programme reproducteurs','duree de carriere','dose unique','0 jour',NULL,'0 jour','reaction respiratoire legere','presence d antibiotiques actifs sur mycoplasmes','ne pas associer a une antibiotherapie anti-mycoplasme','+2 a +8 C','flacon 1000-2000 doses','https://www.woah.org/fr/maladie/mycoplasmose-aviaire/',1),
  (1,'Coryza infectieux','Nobilis Coryza, Coryza Vac','MSD / Ceva','poultry','Coryza infectieux (Avibacterium paragallinarum)','inactive (bacterine) avec adjuvant','0,5 ml','sous-cutane ou intramusculaire','plus de 4 semaines','rappel 4 semaines plus tard','duree de ponte','2 injections','21 jours',NULL,'selon notice','reaction locale au point d injection (nodule)','sujets malades','agiter avant emploi, ramener a temperature ambiante','+2 a +8 C, ne pas congeler','flacon 500-1000 ml','https://www.woah.org/fr/',1),
  (1,'Maladie de Marek','Nobilis Rismavac, Cryomarex','MSD / Boehringer','poultry','Maladie de Marek','vivant (herpesvirus HVT)','1 dose','sous-cutane au couvoir ou in ovo','jour 1 (ou in ovo a J18)','dose unique','a vie','dose unique','0 jour',NULL,'0 jour','aucun effet notable','rupture de chaine du froid (azote liquide)','conservation azote liquide, reconstitution immediate','azote liquide (-196 C)','ampoule sous azote','https://www.woah.org/fr/maladie/maladie-de-marek/',1),
  (1,'Fievre aphteuse (FMD)','Aftovax, Aftopor','Boehringer / Merial','cattle, sheep, goat, pig','Fievre aphteuse','inactive avec adjuvant','2 ml (bovins)','sous-cutane ou intramusculaire','plus de 2 mois','rappel 4 semaines puis tous 6 mois','6 mois','revaccination semestrielle','selon pays','selon pays',NULL,'reaction locale, hyperthermie transitoire, baisse de production laitiere','animaux malades','souche adaptee au serotype circulant (O, A, SAT)','+2 a +8 C, ne pas congeler','flacon 50-100 doses','https://www.woah.org/fr/maladie/fievre-aphteuse/',1),
  (1,'Peste des petits ruminants (PPR)','Pestevac, Nigeria 75/1','divers','sheep, goat','Peste des petits ruminants','vivant attenue','1 ml','sous-cutane','plus de 3 mois','rappel annuel','3 ans','dose unique','0 jour','0 jour',NULL,'hyperthermie passagere','femelles gestantes (prudence)','reconstituer et utiliser dans l heure, a l abri du soleil','+2 a +8 C','flacon 100 doses lyophilise','https://www.woah.org/fr/maladie/peste-des-petits-ruminants/',1),
  (1,'Charbon symptomatique (Blackleg)','Covexin, Bravoxin','MSD / Zoetis','cattle, sheep','Clostridioses (charbon symptomatique, enterotoxemie)','inactive (anatoxine multivalente)','2 ml','sous-cutane','plus de 2 mois','rappel 4-6 semaines puis annuel','12 mois','2 injections puis rappel annuel','selon notice','selon notice',NULL,'nodule au point d injection','animaux malades','agiter, injection en zone propre et seche','+2 a +8 C, ne pas congeler','flacon 50-100 ml','https://www.woah.org/fr/',1),
  (1,'Charbon bacteridien (Anthrax)','Sterne 34F2','divers','cattle, sheep, goat, horse','Charbon bacteridien (Bacillus anthracis)','vivant attenue spore (Sterne)','1 ml','sous-cutane','plus de 6 mois','rappel annuel','12 mois','dose unique annuelle','42 jours','selon notice',NULL,'oedeme transitoire au point d injection','antibiotherapie concomitante (inhibe la souche vivante)','ne pas vacciner sous antibiotiques, manipuler avec precaution (zoonose)','+2 a +8 C','flacon multidose','https://www.woah.org/fr/maladie/fievre-charbonneuse/',1),
  (1,'Brucellose bovine (RB51)','RB51','divers','cattle','Brucellose (Brucella abortus)','vivant attenue (RB51, rough)','2 ml','sous-cutane','genisses 3 a 10 mois','dose unique (selon programme national)','plusieurs annees','dose unique','21 jours','selon notice',NULL,'avortement si vaccine gestante, reaction locale','femelles gestantes, males reproducteurs','zoonose: EPI obligatoire, ne pas s auto-injecter','+2 a +8 C','flacon lyophilise + diluant','https://www.woah.org/fr/maladie/brucellose/',1),
  (1,'Pasteurellose (septicemie hemorragique)','Pastovax','divers','cattle, buffalo, sheep, goat','Pasteurellose / septicemie hemorragique','inactive (bacterine adjuvee)','2-3 ml','sous-cutane','plus de 4 mois','rappel annuel avant la saison des pluies','12 mois','dose unique annuelle','selon notice','selon notice',NULL,'reaction locale, hyperthermie transitoire','animaux malades','vacciner avant la saison a risque','+2 a +8 C, ne pas congeler','flacon multidose','https://www.woah.org/fr/',1),
  (1,'Rage','Rabisin, Nobivac Rabies','Boehringer / MSD','dog, cat, cattle, horse','Rage','inactive','1 ml','sous-cutane ou intramusculaire','plus de 3 mois','rappel a 1 an puis tous 1-3 ans','1 a 3 ans','rappel periodique','selon pays','selon pays',NULL,'reaction locale, abattement transitoire','animaux malades','zoonose mortelle: respecter le calendrier legal','+2 a +8 C, ne pas congeler','flacon 1-10 doses','https://www.woah.org/fr/maladie/rage/',1),
  (1,'Dermatose nodulaire contagieuse (LSD)','Lumpyvax, Kenyavac','MSD / divers','cattle','Dermatose nodulaire contagieuse bovine','vivant attenue','1 ml','sous-cutane','plus de 6 mois','rappel annuel','12 mois','dose unique annuelle','selon notice','selon notice',NULL,'nodules cutanes post-vaccinaux transitoires, leger oedeme','animaux gestants (prudence selon souche)','reconstituer et utiliser rapidement','+2 a +8 C','flacon lyophilise','https://www.woah.org/fr/maladie/dermatose-nodulaire-contagieuse/',1),
  (1,'Clavelee et variole caprine','Sheep pox vaccine','divers','sheep, goat','Clavelee (variole ovine et caprine)','vivant attenue','1 ml','sous-cutane','plus de 3 mois','rappel annuel','12 mois','dose unique annuelle','selon notice','selon notice',NULL,'reaction locale, papule au point d injection','animaux malades','a l abri du soleil apres reconstitution','+2 a +8 C','flacon lyophilise','https://www.woah.org/fr/maladie/clavelee-et-variole-caprine/',1),
  (1,'Maladie de Carre (Distemper)','Nobivac DHPPi, Canigen','MSD / Virbac','dog','Maladie de Carre, parvovirose, hepatite','vivant attenue polyvalent','1 ml','sous-cutane','6 a 8 semaines','rappels 3-4 semaines jusqu a 16 semaines puis annuel','1 an','primo 2-3 injections puis rappel annuel','sans objet','sans objet',NULL,'abattement, leger oedeme','chiots a anticorps maternels','respecter le calendrier de primo-vaccination','+2 a +8 C','flacon unidose + diluant','https://wsava.org/global-guidelines/vaccination-guidelines/',1),
  (1,'Parvovirose canine','Nobivac Parvo-C','MSD','dog','Parvovirose canine','vivant attenue','1 ml','sous-cutane','6 a 8 semaines','rappels jusqu a 16 semaines puis annuel ou triennal','1 a 3 ans','primo puis rappels','sans objet','sans objet',NULL,'abattement transitoire','chiots malades','hygiene stricte en environnement contamine','+2 a +8 C','flacon unidose','https://wsava.org/global-guidelines/vaccination-guidelines/',1),
  (1,'Peste porcine classique (CSF)','Pestiffa, souche C','Boehringer / divers','pig','Peste porcine classique','vivant attenue (souche chinoise C)','2 ml','intramusculaire','plus de 4 semaines','rappel selon programme','plus de 1 an','dose unique ou selon plan','selon pays','sans objet',NULL,'hyperthermie passagere','truies en fin de gestation (prudence)','ne pas confondre avec la peste porcine africaine (pas de vaccin)','+2 a +8 C','flacon lyophilise','https://www.woah.org/fr/maladie/peste-porcine-classique/',1),
  (1,'Rouget du porc','Eryseng, Porcilis Ery','Hipra / MSD','pig','Rouget (Erysipelothrix rhusiopathiae)','inactive','2 ml','intramusculaire','plus de 6 semaines','rappel 3-4 semaines puis tous 6 mois','6 mois','2 injections puis rappel','selon notice','sans objet',NULL,'reaction locale, hyperthermie transitoire','animaux malades','agiter avant emploi','+2 a +8 C, ne pas congeler','flacon 20-50 doses','https://www.woah.org/fr/',1),
  (1,'Parvovirose et rouget porcin','Eryseng Parvo, Parvoruvax','Hipra / Ceva','pig','Parvovirose porcine et rouget','inactive (combine)','2 ml','intramusculaire','cochettes avant saillie','rappel avant chaque gestation','6 mois','2 injections de primo puis rappel par cycle','selon notice','sans objet',NULL,'reaction locale','verrats et truies malades','vacciner avant la mise a la reproduction','+2 a +8 C','flacon 25-50 doses','https://www.woah.org/fr/',1),
  (1,'Colibacillose neonatale (E. coli)','Coliprotec, Porcilis Coli','Elanco / MSD','pig, cattle','Colibacillose neonatale (diarrhees du nouveau-ne)','inactive (meres gestantes)','2 ml','intramusculaire','meres en fin de gestation','rappel a chaque gestation','par cycle (immunite passive colostrale)','2 injections avant mise bas','selon notice','selon notice',NULL,'reaction locale','meres malades','protection des petits via le colostrum: vacciner la mere','+2 a +8 C','flacon multidose','https://www.woah.org/fr/',1),
  (1,'Salmonellose aviaire (S. Enteritidis)','Nobilis Salenvac, AviPro Salmonella','MSD / Elanco','poultry','Salmonellose (S. Enteritidis et Typhimurium)','inactive ou vivant attenue','0,5 ml (inactive) ou 1 dose orale','intramusculaire ou eau de boisson','des le 1er jour (vivant) ou poulettes (inactive)','rappels selon programme ponte','duree de ponte','programme repete','selon notice',NULL,'selon notice','reaction locale (forme injectable)','sujets malades','important pour la securite sanitaire des oeufs','+2 a +8 C','flacon multidose','https://www.woah.org/fr/',1),
  (1,'Coccidiose aviaire','Paracox, Hipracox','MSD / Hipra','poultry','Coccidiose (Eimeria spp.)','vivant (oocystes attenues)','1 dose','eau de boisson, spray ou sur aliment','jour 1 a 5','dose unique (immunite par cyclage)','duree d elevage','dose unique','0 jour',NULL,'0 jour','leger ralentissement de croissance transitoire','traitement anticoccidien concomitant (incompatible)','ne pas utiliser d anticoccidiens en parallele','+2 a +8 C','flacon multidose','https://www.woah.org/fr/',1),
  (1,'Enterotoxemie (Clostridium perfringens)','Covexin 8, Bravoxin 10','MSD / Zoetis','sheep, goat, cattle','Enterotoxemies clostridiennes','inactive (anatoxine multivalente)','2 ml','sous-cutane','plus de 1 mois (apres colostrum)','rappel 4-6 semaines puis annuel','12 mois','2 injections puis rappel annuel','selon notice','selon notice',NULL,'nodule au point d injection','animaux malades','vacciner les meres pour proteger les jeunes via le colostrum','+2 a +8 C, ne pas congeler','flacon 50-100 ml','https://www.woah.org/fr/',1);
