/* eslint-disable */
// FarmOS Pro - UI species registry and i18n. Business data comes from API/DB.
// The species registry drives UI fields, modules, labels and units only.

// ─── i18n ────────────────────────────────────────────────────────────────
const I18N = {
  fr: {
    appName: "FarmOS Pro",
    tagline: "Élevage intelligent",
    // Nav
    dashboard: "Tableau de bord",
    identification: "Identification",
    animals: "Animaux",
    buildings: "Bâtiments",
    health: "Santé & traitements",
    calendar: "Calendrier vaccinal",
    stock: "Stock & alimentation",
    feed: "Aliments",
    medicines: "Médicaments",
    repro: "Reproduction",
    semenBank: "Banque de semence",
    production: "Production",
    alerts: "Alertes",
    pos: "POS",
    salesManagement: "Gestion de vente",
    finances: "Finances",
    reports: "Rapports",
    employees: "Employés",
    settings: "Paramètres",
    // Generic
    search: "Rechercher",
    new: "Nouveau",
    filter: "Filtrer",
    export: "Exporter",
    syncOk: "Synchronisé · à l'instant",
    allSpecies: "Toutes espèces",
    today: "Aujourd'hui",
    yesterday: "Hier",
    week: "7 jours",
    month: "30 jours",
    quarter: "Trimestre",
    year: "Année",
    // KPIs
    kTotal: "Cheptel total",
    kSick: "Animaux malades",
    kQuarantine: "En quarantaine",
    kMortality: "Mortalité (30 j)",
    kProd: "Production · jour",
    kRevenue: "Revenus · mois",
    kExpense: "Dépenses · mois",
    kFeedStock: "Stock alimentation",
    kMedStock: "Stock médicaments",
    kTreatments: "Traitements actifs",
    kVaccinesLate: "Vaccins en retard",
    kAlerts: "Alertes critiques",
    kRepro: "Gestations en cours",
    kSales: "Ventes (sem.)",
    // Withdrawal
    withdrawal: "Délai de retrait non terminé",
    withdrawalSub: "Vente, abattage et collecte bloqués",
    // Sections
    overview: "Vue d'ensemble",
    bySpecies: "Par espèce",
    aiInsights: "Recommandations IA",
    nextActions: "Prochaines actions",
    upcoming: "À venir",
    recent: "Récent",
    // Health
    diseases: "Maladies actives",
    treatments: "Traitements",
    vaccines: "Vaccination",
    vet: "Vétérinaire",
    quarantine: "Quarantaine",
    // Repro & prod
    heat: "Chaleurs",
    gestation: "Gestation",
    birthing: "Mises bas",
    milk: "Lait",
    eggs: "Œufs",
    meat: "Viande",
    wool: "Laine",
    growth: "Croissance",
    // Finance
    revenue: "Revenus",
    expense: "Dépenses",
    profit: "Profit net",
    margin: "Marge",
  },
  en: {
    appName: "FarmOS Pro",
    tagline: "Smart livestock",
    dashboard: "Dashboard",
    identification: "Identification",
    animals: "Animals",
    buildings: "Buildings",
    health: "Health & treatments",
    calendar: "Vaccination calendar",
    stock: "Stock & feed",
    feed: "Feed",
    medicines: "Medicines",
    repro: "Reproduction",
    semenBank: "Semen bank",
    production: "Production",
    alerts: "Alerts",
    pos: "POS",
    salesManagement: "Sales management",
    finances: "Finances",
    reports: "Reports",
    employees: "Employees",
    settings: "Settings",
    search: "Search",
    new: "New",
    filter: "Filter",
    export: "Export",
    syncOk: "Synced · just now",
    allSpecies: "All species",
    today: "Today",
    yesterday: "Yesterday",
    week: "7 days",
    month: "30 days",
    quarter: "Quarter",
    year: "Year",
    kTotal: "Total herd",
    kSick: "Sick animals",
    kQuarantine: "In quarantine",
    kMortality: "Mortality (30 d)",
    kProd: "Production · day",
    kRevenue: "Revenue · month",
    kExpense: "Expenses · month",
    kFeedStock: "Feed stock",
    kMedStock: "Medicine stock",
    kTreatments: "Active treatments",
    kVaccinesLate: "Vaccines overdue",
    kAlerts: "Critical alerts",
    kRepro: "Active gestations",
    kSales: "Sales (week)",
    withdrawal: "Withdrawal period not cleared",
    withdrawalSub: "Sale, slaughter and collection blocked",
    overview: "Overview",
    bySpecies: "By species",
    aiInsights: "AI insights",
    nextActions: "Next actions",
    upcoming: "Upcoming",
    recent: "Recent",
    diseases: "Active diseases",
    treatments: "Treatments",
    vaccines: "Vaccination",
    vet: "Veterinarian",
    quarantine: "Quarantine",
    heat: "Heat cycles",
    gestation: "Gestation",
    birthing: "Birthing",
    milk: "Milk",
    eggs: "Eggs",
    meat: "Meat",
    wool: "Wool",
    growth: "Growth",
    revenue: "Revenue",
    expense: "Expenses",
    profit: "Net profit",
    margin: "Margin",
  },
};

const t = (lang, key) => (I18N[lang] && I18N[lang][key]) || key;

// ─── Species registry ────────────────────────────────────────────────────
// Each entry drives form fields, modules, labels and units.
const SPECIES = [
  {
    id: "cow",
    glyph: "cow",
    fr: "Vaches",            en: "Cattle",
    frSing: "Vache",         enSing: "Cow",
    accent: "var(--pertinence-700)",
    accentBg: "var(--pertinence-50)",
    countingUnit: "tête",
    productPrimary: "milk",      // milk, eggs, meat, wool, growth, fish
    productLabel:  { fr: "Lait · L/j",   en: "Milk · L/d" },
    housingLabel:  { fr: "Bâtiment & enclos",   en: "Barn & paddock" },
    repro: ["heat", "ai", "gestation", "calving", "fertility", "calf-history"],
    diseases: [],
    diseasesEn: [],
    alerts: [],
    alertsEn: [],
    fields: ["tag", "ear-loop", "race", "sex", "dob", "weight", "color", "barn", "lot", "lactation", "rumination", "temp", "ai-history"],
    modules: ["health", "milk", "repro", "feed", "finance"],
  },
  {
    id: "pig",
    glyph: "pig",
    fr: "Porcs",             en: "Pigs",
    frSing: "Porc",          enSing: "Pig",
    accent: "var(--oxblood-700)",
    accentBg: "var(--oxblood-50)",
    countingUnit: "tête",
    productPrimary: "growth",
    productLabel:  { fr: "GMQ · g/j",   en: "ADG · g/d" },
    housingLabel:  { fr: "Salle, lot & enclos",   en: "Room, batch & pen" },
    repro: ["heat", "ai", "gestation", "farrow", "litter", "weaning"],
    diseases: [],
    diseasesEn: [],
    alerts: [],
    alertsEn: [],
    fields: ["tag", "type", "race", "sex", "dob", "weight", "lot", "room", "fcr", "weaning-w", "litter-id"],
    modules: ["health", "growth", "repro", "feed", "finance", "biosec"],
  },
  {
    id: "chicken",
    glyph: "chicken",
    fr: "Poulets",           en: "Chickens",
    frSing: "Poulet",        enSing: "Chicken",
    accent: "var(--autorite-700)",
    accentBg: "var(--autorite-50)",
    countingUnit: "lot",
    productPrimary: "eggs",
    productLabel:  { fr: "Œufs · jour",   en: "Eggs · day" },
    housingLabel:  { fr: "Bâtiment & lot",   en: "House & batch" },
    repro: [],
    diseases: [],
    diseasesEn: [],
    alerts: [],
    alertsEn: [],
    fields: ["batch-id", "count", "age", "race", "weight-avg", "house", "temp", "humidity", "lay-rate"],
    modules: ["health", "eggs", "growth", "feed", "finance", "biosec"],
  },
  {
    id: "fish",
    glyph: "fish",
    fr: "Poissons",          en: "Fish",
    frSing: "Bassin",        enSing: "Pond",
    accent: "var(--pertinence-700)",
    accentBg: "var(--pertinence-50)",
    countingUnit: "bassin",
    productPrimary: "growth",
    productLabel:  { fr: "Biomasse · kg",   en: "Biomass · kg" },
    housingLabel:  { fr: "Bassin & circuit",   en: "Pond & circuit" },
    repro: [],
    diseases: [],
    diseasesEn: [],
    alerts: [],
    alertsEn: [],
    fields: ["pond-id", "species", "density", "oxygen", "ph", "temp-water", "weight-avg", "biomass"],
    modules: ["health", "growth", "feed", "finance", "water"],
  },
  {
    id: "goat",
    glyph: "goat",
    fr: "Chèvres",           en: "Goats",
    frSing: "Chèvre",        enSing: "Goat",
    accent: "var(--solidite-700)",
    accentBg: "var(--solidite-50)",
    countingUnit: "tête",
    productPrimary: "milk",
    productLabel:  { fr: "Lait · L/j",   en: "Milk · L/d" },
    housingLabel:  { fr: "Bâtiment & pâturage",   en: "Barn & pasture" },
    repro: ["heat", "kidding", "fertility"],
    diseases: [],
    diseasesEn: [],
    alerts: [],
    alertsEn: [],
    fields: ["tag", "race", "sex", "dob", "weight", "pasture", "lactation"],
    modules: ["health", "milk", "repro", "feed", "finance"],
  },
  {
    id: "sheep",
    glyph: "sheep",
    fr: "Moutons",           en: "Sheep",
    frSing: "Mouton",        enSing: "Sheep",
    accent: "var(--autorite-700)",
    accentBg: "var(--autorite-50)",
    countingUnit: "tête",
    productPrimary: "wool",
    productLabel:  { fr: "Tonte · kg",   en: "Shearing · kg" },
    housingLabel:  { fr: "Pâturage & bergerie",   en: "Pasture & fold" },
    repro: ["heat", "lambing", "fertility"],
    diseases: [],
    diseasesEn: [],
    alerts: [],
    alertsEn: [],
    fields: ["tag", "race", "sex", "dob", "weight", "pasture", "wool-quality"],
    modules: ["health", "wool", "repro", "feed", "finance"],
  },
  {
    id: "rabbit",
    glyph: "rabbit",
    fr: "Lapins",            en: "Rabbits",
    frSing: "Lapin",         enSing: "Rabbit",
    accent: "var(--oxblood-700)",
    accentBg: "var(--oxblood-50)",
    countingUnit: "tête",
    productPrimary: "growth",
    productLabel:  { fr: "Croissance · g/j",   en: "Growth · g/d" },
    housingLabel:  { fr: "Cage & rangée",   en: "Cage & row" },
    repro: ["mating", "kindling", "litter", "weaning"],
    diseases: [],
    diseasesEn: [],
    alerts: [],
    alertsEn: [],
    fields: ["tag", "race", "sex", "dob", "weight", "cage", "litter-id"],
    modules: ["health", "growth", "repro", "feed", "finance"],
  },
  {
    id: "duck",
    glyph: "duck",
    fr: "Canards",           en: "Ducks",
    frSing: "Canard",        enSing: "Duck",
    accent: "var(--solidite-700)",
    accentBg: "var(--solidite-50)",
    countingUnit: "lot",
    productPrimary: "eggs",
    productLabel:  { fr: "Œufs · jour",   en: "Eggs · day" },
    housingLabel:  { fr: "Bâtiment & bassin",   en: "House & pond" },
    repro: ["lay-rate"],
    diseases: [],
    diseasesEn: [],
    alerts: [],
    alertsEn: [],
    fields: ["batch-id", "count", "age", "house", "lay-rate", "pond"],
    modules: ["health", "eggs", "feed", "finance", "biosec"],
  },
  {
    id: "turkey",
    glyph: "turkey",
    fr: "Dindes",            en: "Turkeys",
    frSing: "Dinde",         enSing: "Turkey",
    accent: "var(--autorite-700)",
    accentBg: "var(--autorite-50)",
    countingUnit: "lot",
    productPrimary: "growth",
    productLabel:  { fr: "Poids moyen · kg",   en: "Avg weight · kg" },
    housingLabel:  { fr: "Bâtiment & lot",   en: "House & batch" },
    repro: [],
    diseases: [],
    diseasesEn: [],
    alerts: [],
    alertsEn: [],
    fields: ["batch-id", "count", "age", "house", "weight-avg", "fcr"],
    modules: ["health", "growth", "feed", "finance", "biosec"],
  },
];

const speciesById = (id) => SPECIES.find((s) => s.id === id);

// ─── Aggregate totals (computed) ─────────────────────────────────────────
// Business data must come from the FarmOS API/DB. These exports stay empty so
// legacy imports fail closed instead of rendering sample farm records.
const TOTALS = { count: 0, sick: 0, mortality: 0, speciesCount: SPECIES.length };
const ANIMALS = [];
const ALERTS = [];
const TREATMENTS = [];
const VACCINES = [];
const STOCK = [];
const FINANCE = { revenue: [], expense: [], byCategory: [] };
const AI_INSIGHTS = [];

export { I18N, t, SPECIES, speciesById, TOTALS, ANIMALS, ALERTS, TREATMENTS, VACCINES, STOCK, FINANCE, AI_INSIGHTS };
